title: "Omnitryx Inc."
description: "Premium digital services & automation."

url: "https://omnitryx.ca"
baseurl: ""
logo: "/assets/images/logo.png"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  services:
    output: true
    permalink: /services/:name/

include:
  - pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      description: "Omnitryx provides premium digital services, automation, and development."

  - scope:
      path: "services"
      type: "services"
    values:
      layout: "service"

  - scope:
      path: "legal"
    values:
      layout: "default"

permalink: /:title/

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - _site
  - .gitignore
  - .DS_Store